"""empty message

Revision ID: 2ec12d78f574
Revises: b36f10132711
Create Date: 2025-06-13 23:21:00.702763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec12d78f574'
down_revision = 'b36f10132711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuarioId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['usuarioId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuarioId')

    # ### end Alembic commands ###
