"""empty message

Revision ID: e0cc4d174882
Revises: ea62d6a1764e
Create Date: 2025-06-13 23:11:21.077369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cc4d174882'
down_revision = 'ea62d6a1764e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuarioId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['usuarioId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuarioId')

    # ### end Alembic commands ###
